- name: Install redis package
  package:
    name: redis
    state: present

- name: Install Redis config file
  template:
    src: redis.conf.j2
    dest: /usr/local/etc/redis.conf
    mode: 0644
    owner: root
    group: wheel

- name: Install Redis RC config
  copy:
    src: rc.redis.conf
    dest: /etc/rc.conf.d/redis
    mode: 0644
    owner: root
    group: wheel

- name: Ensure Redis is running
  service:
    name: redis
    state: started
