language: generic
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

before_install:
  # Install Bazel
  - sudo curl -L https://github.com/bazelbuild/bazel/releases/download/3.6.0/bazel-3.6.0-linux-arm64 -o /usr/local/bin/bazel
  - sudo chmod +x /usr/local/bin/bazel

  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Make sure we still get the failure from Bazel even though we pipe it.
  - set -o pipefail

  # Run tests
  - bazel test --config=ci //...

  # Build and push container images, and output the Kubernetes configs.
  - bazel run --config=ci all_k8s > /tmp/all_k8s.yaml

cache:
  directories:
    - $HOME/.cache/bazel/disk-cache

before_deploy:
  - mkdir -p /tmp/s3_staging/$TRAVIS_COMMIT /tmp/s3_staging/latest
  - cp /tmp/all_k8s.yaml /tmp/s3_staging/$TRAVIS_COMMIT/all_k8s.yaml
  - echo "$TRAVIS_COMMIT" > /tmp/s3_staging/latest/$TRAVIS_BRANCH.txt

deploy:
  edge: true
  provider: s3
  bucket: pi-tools-builds
  region: us-east-2
  local_dir: /tmp/s3_staging
  on:
    all_branches: true
