listen:
  address: :9130
  metricspath: /metrics
unifi:
  address: https://10.0.0.1
  username: mmoriarity
  password: {{ with secret "kv/unifi-exporter" }}{{ .Data.data.unifi_password }}{{ end }}
  site: Default
  insecure: true
  timeout: 10s
  unifi_os: true
