apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pi-hole
  name: pi-hole-data-nfs
  annotations:
    nfs.io/storage-path: pi-hole-data
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
