apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: promtail
          image: index.docker.io/mmoriarity/promtail:latest
          args:
            - "-config.file=/etc/promtail/promtail.yml"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: "100m"
              memory: "50M"
            limits:
              memory: "100M"
          ports:
            - name: http
              containerPort: 3101
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: run
              mountPath: /run/promtail
            - name: var-journal
              mountPath: /var/log/journal
              readOnly: true
            - name: run-journal
              mountPath: /run/log/journal
              readOnly: true
            - name: machine-id
              mountPath: /etc/machine-id
              readOnly: true
      volumes:
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: run
          hostPath:
            path: /run/promtail
        - name: var-journal
          hostPath:
            path: /var/log/journal
        - name: run-journal
          hostPath:
            path: /run/log/journal
        - name: machine-id
          hostPath:
            path: /etc/machine-id
