---
ansible_ssh_host: ci1@artemis.homelab

vault_agent_enabled: true
vault_role_id: 5108b274-5fc3-5f3d-96a1-f9fffc4d6256
vault_agent_user: teamcity
vault_agent_group: teamcity
vault_agent_templates: |
  {% raw %}
  template {
    contents = <<EOF
  {{ with secret "ssh-client-signer/sign/homelab-client" (printf "public_key=%s" (file "/opt/TeamCity/.ssh/id_rsa.pub")) "valid_principals=ubuntu,matt" }}
  {{ .Data.signed_key }}
  {{ end }}
  EOF
    destination = "/opt/TeamCity/.ssh/signed-cert.pub"
  }
  {% endraw %}
