---
ansible_ssh_host: code1@artemis.homelab

vault_agent_enabled: true
vault_role_id: 3364366b-9b6f-9139-ca61-6b82bb1516d3
vault_agent_user: root
vault_agent_group: wheel
vault_agent_templates: |
  {% raw %}
  template {
    source      = "/usr/local/etc/phabricator.conf.tpl"
    destination = "/usr/local/lib/php/phabricator/conf/local/local.json"
    command     = "service phd restart"
  }
  {% endraw %}
