---
ansible_ssh_host: paperless1@artemis.homelab

vault_agent_enabled: true
vault_role_id: 11a736d8-ef30-f7aa-1d1e-72029ce45fb4
vault_agent_user: root
vault_agent_group: wheel
vault_agent_templates: |
  {% raw %}
  template {
    source      = "/usr/local/etc/paperless.conf.tpl"
    destination = "/usr/local/etc/paperless.conf"
    command     = "/usr/local/bin/paperless-restart"
  }
  {% endraw %}
