apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
spec:
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: monitoring
  name: grafana
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 3000
