---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: grafana-data
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-data
spec:
  storageClassName: ""
  volumeName: grafana-data
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 256Mi
