apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: grafana-data-nfs
  annotations:
    nfs.io/storage-path: grafana-data
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
