apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: detect-presence
  name: beacon-srv
  labels:
    app: beacon
spec:
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      # this is what lets us talk to the bluetooth device
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - raspberrypi
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            # do not allow scheduling on the same node that is running detect-presence-srv, in case this advertising
            # interferes with the other bluetooth things that it does
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: detect-presence
      containers:
        - name: beacon-srv
          image: index.docker.io/mmoriarity/beacon-srv:latest
          command:
            - /beacon-srv
            - -proximity-uuid
            - 7298c12b-f658-445f-b1f2-5d6d582f0fb0
            - -node-name
            - $(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: "50m"
              memory: "30M"
            limits:
              memory: "40M"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
