apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - image: index.docker.io/mmoriarity/loki:latest
          name: loki
          args:
            - "-config.file=/etc/loki/loki.yml"
          resources:
            requests:
              cpu: "50m"
              memory: "75M"
            limits:
              memory: "150M"
          ports:
            - containerPort: 3100
              name: http
              protocol: TCP
          volumeMounts:
            - name: loki-data
              mountPath: /data
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: loki-data
          emptyDir: {}
