apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      hostNetwork: true
      initContainers:
        - name: substitute-secrets
          image: index.docker.io/mmoriarity/alertmanager:latest
          command:
            - /bin/substitute-secrets
          envFrom:
            - secretRef:
                name: alertmanager
      containers:
        - name: alertmanager
          image: index.docker.io/mmoriarity/alertmanager:latest
          ports:
            - name: http
              containerPort: 9093
              hostPort: 9093
          volumeMounts:
            - name: alertmanager-data
              mountPath: /alertmanager
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
      volumes:
        - name: alertmanager-data
          emptyDir: {}
