apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        linkerd.io/inject: enabled
    spec:
      initContainers:
        - name: substitute-secrets
          image: index.docker.io/mmoriarity/alertmanager:latest
          command:
            - /bin/substitute-secrets
          envFrom:
            - secretRef:
                name: alertmanager
          volumeMounts:
            - name: alertmanager-config
              mountPath: /cfg/alertmanager
      containers:
        - name: alertmanager
          image: index.docker.io/mmoriarity/alertmanager:latest
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.external-url=https://alertmanager.homelab/
          resources:
            requests:
              cpu: "50m"
              memory: "50M"
            limits:
              memory: "100M"
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: alertmanager-data
              mountPath: /alertmanager
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
              readOnly: true
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
      volumes:
        - name: alertmanager-data
          emptyDir: {}
        - name: alertmanager-config
          emptyDir: {}
