- name: Install consul-template
  package:
    name: consul-template
    state: present

- name: Install consul-template RC config
  copy:
    src: consul_template
    dest: /etc/rc.conf.d/consul_template
    mode: 0644
    owner: root
    group: wheel

- name: Create consul-template config directory
  file:
    path: /usr/local/etc/consul-template.d
    state: directory
    mode: 0700
    owner: root
    group: wheel

- name: Copy common consul-template config
  template:
    src: common.hcl.j2
    dest: /usr/local/etc/consul-template.d/common.hcl
    mode: 0644
    owner: root
    group: wheel
  notify: Reload consul-template config

- name: Install consul-template tokens config
  template:
    src: tokens.hcl.j2
    dest: /usr/local/etc/consul-template.d/tokens.hcl
    mode: 0600
    owner: root
    group: wheel
  notify: Reload consul-template config

- name: Ensure consul-template is running and starts at boot
  service:
    name: consul-template
    state: started
    enabled: true
