groups:
  - name: dns_alerts
    rules:
      - alert: ExternalDNSFailing
        expr: probe_success{probe_type="dns",instance!~"10.0.0.[2-4]"} < 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: External DNS queries are failing
          description: >
            One or more external DNS servers are unable to look up Google's home page.
            This might mean your internet is down, though I'm not sure how you're getting this alert
            in that case.

      - alert: DNSFailingExternalSite
        expr: (min(probe_success{probe_type="dns",instance!~"10.0.0.[2-4]"}) > 0.5) and (min(probe_success{probe_type="dns",probe_scope="public",instance=~"10.0.0.[2-4]"}) < 0.5)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: DNS queries for external sites are failing
          description: >
            The PiHole is unable to look up Google's home page, but external DNS is able to look it up
            without issue. Something is probably wrong with PiHole's configuration.

      - alert: DNSFailingInternalNode
        expr: probe_success{probe_type="dns",probe_scope="private"} < 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: DNS queries for Raspberry Pi nodes are failing
          description: >
            A DNS server is unable to look up the address for the raspberrypi node, or it's not giving
            the expected IP address.

      - alert: DNSFailingInternalSite
        expr: probe_success{probe_type="dns",probe_scope="private-cname"} < 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: DNS queries for internal sites are failing
          description: >
            The PiHole is unable to look up the address for Homebase, or it's not returning a CNAME to a
            Raspberry Pi node.
