groups:
  - name: homebase_bot_alerts
    rules:
      - alert: HomebaseBotServiceDown
        expr: sum(up{app="homebase-bot"}) < 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: No homebase-bot-srv instances are running
          description: >
            There don't seem to be any running pods of homebase-bot-srv. The Telegram bot won't work until
            this is addressed.

      - alert: HomebaseBotNoLeader
        expr: sum(homebase_bot_is_leader) < 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: homebase-bot-srv has no leader
          description: >
            There are no homebase-bot-srv pods acting as leader. The Telegram bot won't be able to respond to
            incoming messages until there is a leader.
