groups:
  - name: k8s_alerts
    rules:
      - alert: KubeAPIUnreachable
        expr: probe_success{job="blackbox-kubernetes-api"} < 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes API is not reachable
          description: >
            Attempts to access the Kubernetes API are failing. Check on the host that's failing, and consider restarting
            the Kubernetes apiserver.

      - alert: KubeAPIServerHighMemory
        expr: process_resident_memory_bytes{job="kubernetes-apiservers"} > 2500000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes apiserver is using too much memory
          description: >
            If its memory use continues growing, it may cause the Raspberry Pi to freeze up and become unreachable.
            You should probably restart the apiserver manually by running
            `sudo systemctl restart snap.microk8s.daemon-apiserver`.

            If this continues to happen regularly, you should automate restarting the apiserver regularly.

      - alert: KubeAPIServerDown
        expr: sum(up{job="kubernetes-apiservers"}) < 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes apiserver is down
          description: >
            One or more Kubernetes apiserver instances is not able to be scraped by Prometheus.

      - alert: KubeletDown
        expr: sum(up{job="kubernetes-nodes"}) < 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes node is down
          description: >
            One or more kubelet instances is not able to be scraped by Prometheus.
