groups:
  - name: node_alerts
    rules:
      - alert: NodeExporterDown
        expr: up{app="node-exporter"} < 0.5
        for: 5m
        labels:
          severity: notice
        annotations:
          summary: Node exporter is down
          annotations: >
            One or more of the node-exporters can't be scraped by Prometheus. You should look into this, as you're
            probably missing some metrics you'd like to have.

      - alert: NodeTemperatureTooHigh
        expr: node_hwmon_temp_celsius > 80
        for: 5m
        labels:
          severity: notice
        annotations:
          summary: Raspberry Pi temperature is close to throttling
          description: >
            One or more Raspberry Pis are approaching a temperature that will cause the CPU to start
            throttling.

      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{device!~'rootfs',mountpoint="/"} / node_filesystem_size_bytes{device!~'rootfs',mountpoint="/"}) < 0.05
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Raspberry Pi is running out of disk space
          description: >
            One or more Raspberry Pis have less than 5% space available on their root volume.

      - alert: HighMemoryUsage
        expr: (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) < 300000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Raspberry Pi is using too much memory
          description: >
            One or more Raspberry Pis is using a lot of memory. Some process on the machine probably needs to
            be restarted.
