- name: Copy package list
  copy:
    src: pkglist
    dest: /usr/local/etc/pkglist
    mode: 0644
    owner: root
    group: wheel
  # sloppy way of only doing this on artemis and not in each jail
  when: inventory_hostname == 'artemis'

- name: Create directory for local package repos
  file:
    path: /usr/local/etc/pkg/repos
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Disable default FreeBSD package repo
  copy:
    src: FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    mode: 0644
    owner: root
    group: wheel

- name: Install local package repo
  copy:
    src: amd64-current.conf
    dest: /usr/local/etc/pkg/repos/amd64-current.conf
    mode: 0644
    owner: root
    group: wheel
