apiVersion: v1
kind: Service
metadata:
  namespace: storage
  name: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
