apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: storage
  name: postgresql
  labels:
    app: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: postgresql
          image: index.docker.io/postgres@sha256:b6399aef923e0529a4f2a5874e8860d29cef3726ab7079883f3368aaa2a9f29c
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD_FILE
              value: /var/secrets/pg-password
          resources:
            requests:
              cpu: "100m"
              memory: "300M"
            limits:
              memory: "500M"
          volumeMounts:
            - name: secrets
              mountPath: /var/secrets
              readOnly: true
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: secrets
          secret:
            secretName: postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        storageClassName: ""
        volumeName: postgresql-data-0
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 3Gi
