apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-0
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: postgresql-0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
