apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: {{ with service "prometheus" }}{{ with index . 0 }}http://{{ .Address }}:{{ .Port }}{{ end }}{{ end }}
    isDefault: true
    version: 1
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
  - name: Jaeger
    type: jaeger
    access: proxy
    url: {{ with service "jaeger-query" }}{{ with index . 0 }}http://{{ .Address }}:{{ .Port }}{{ end }}{{ end }}
    version: 1
    editable: false
