- name: Reload Prometheus config
  command:
    cmd: service -j {{ jail_name }} prometheus reload
    warn: false
  become: true

- name: Reload consul-template config
  command: jexec {{ jail_name }} pkill -HUP consul-template
  become: true
