- name: Reload Prometheus config
  service:
    name: prometheus
    state: reloaded
  become: true

- name: Reload Alertmanager config
  service:
    name: alertmanager
    state: reloaded
  become: true

- name: Reload consul-template config
  command: pkill -HUP consul-template
  become: true
