apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: jaeger-operator
spec:
  replicas: 0
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: jaeger-operator
  template:
    metadata:
      labels:
        name: jaeger-operator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8383"
    spec:
      serviceAccountName: jaeger-operator
      containers:
        - name: jaeger-operator
          image: jaegertracing/jaeger-operator@sha256:82016177ea051f2bd0944b36f224e07108e1bfc1d52ec9895bb4163d5836ffec
          ports:
            - containerPort: 8383
              name: http-metrics
            - containerPort: 8686
              name: cr-metrics
          args: ["start"]
          env:
            - name: WATCH_NAMESPACE
              value: monitoring
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "jaeger-operator"
