apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  namespace: monitoring
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    # TODO replace with official Jaeger all-in-one image once they publish a multiarch image
    # https://github.com/jaegertracing/jaeger/pull/2325
    image: querycapistio/all-in-one@sha256:ad4552a9facb5e71ea2ca296fb92cf510e97783ad5068f5d23a6b169edb4a9dd
  ingress:
    hosts:
      - jaeger
