---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: monitoring
  name: jaeger-redirect
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "http://jaeger.homelab/$1"
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
    - host: jaeger
      http:
        paths:
          - path: "/(.*)"
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
  tls:
    - hosts:
        - jaeger
      secretName: jaeger-redirect-cert
