apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: unifi-exporter
  labels:
    app: unifi-exporter
spec:
  selector:
    matchLabels:
      app: unifi-exporter
  template:
    metadata:
      labels:
        app: unifi-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9130"
    spec:
      containers:
        - name: unifi-exporter
          image: index.docker.io/mmoriarity/unifi_exporter:latest
          command:
            - /unifi_exporter
            - -config.file=/config.yml
          resources:
            requests:
              cpu: "100m"
              memory: "30M"
            limits:
              memory: "50M"
          ports:
            - name: http
              containerPort: 9130
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: unifi-exporter
