apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: backup
  name: tarsnap-backup-daily
spec:
  concurrencyPolicy: Forbid
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800 # 7 days
      template:
        spec:
          # Always schedule on this node, as it's the one with all the content on it
          nodeName: raspberrypi
          restartPolicy: Never
          initContainers:
            - name: prepare-postgres-dump-presence
              # keep in sync with the image in storage/postgresql/statefulset.yaml
              image: index.docker.io/postgres@sha256:b6399aef923e0529a4f2a5874e8860d29cef3726ab7079883f3368aaa2a9f29c
              command:
                - pg_dump
                - --host=postgresql.storage
                - --dbname=presence
                - --user=postgres
                - --file=/backup/presence.sql
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: pg-password
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: postgresql-secrets
                  mountPath: /var/secrets
            - name: prepare-postgres-dump-golinks
              # keep in sync with the image in storage/postgresql/statefulset.yaml
              image: index.docker.io/postgres@sha256:b6399aef923e0529a4f2a5874e8860d29cef3726ab7079883f3368aaa2a9f29c
              command:
                - pg_dump
                - --host=postgresql.storage
                - --dbname=golinks
                - --user=postgres
                - --file=/backup/golinks.sql
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: pg-password
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: postgresql-secrets
                  mountPath: /var/secrets
            - name: prepare-postgres-dump-homebasebot
              # keep in sync with the image in storage/postgresql/statefulset.yaml
              image: index.docker.io/postgres@sha256:b6399aef923e0529a4f2a5874e8860d29cef3726ab7079883f3368aaa2a9f29c
              command:
                - pg_dump
                - --host=postgresql.storage
                - --dbname=homebase_bot
                - --user=postgres
                - --file=/backup/homebase_bot.sql
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: pg-password
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: postgresql-secrets
                  mountPath: /var/secrets
            - name: prepare-sqlite3-dump-grafana
              image: index.docker.io/mmoriarity/sqlite3@sha256:3abbdfc0ca66e4cbb31a0fb6dd3d9f7bdc9342d379b8c2e6ae264f3a91a69f61
              command:
                - sh
                - -c
                - "sqlite3 /grafana-data/grafana.db .dump > /backup/grafana.sql"
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: nfs-data
                  mountPath: /grafana-data
                  subPath: monitoring/grafana-data
            - name: prepare-prometheus
              image: index.docker.io/mmoriarity/prometheus-backup:latest
              command:
                - /prometheus-backup
                - -prometheus-url
                - http://prometheus.monitoring
                - -prometheus-data-path
                - /prometheus-data
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: nfs-data
                  mountPath: /prometheus-data
                  subPath: monitoring/prometheus-data
          containers:
            - name: tarsnap
              image: index.docker.io/mmoriarity/tarsnap@sha256:4deeb35783541c160a09cb7a58489a7bf57bb456f4efab83e0cbd663a60bbf50
              command:
                - tarsnap
                - -c
                - --keyfile
                - /var/secrets/tarsnap.key
                - --cachedir
                - /var/lib/tarsnap/cache
                - -f
                - $(POD_NAME)
                - --no-default-config
                - --checkpoint-bytes
                - 1G
                - --print-stats
                - -v
                - /backup
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              volumeMounts:
                - name: backup
                  mountPath: /backup
                  readOnly: true
                - name: tarsnap-cache
                  mountPath: /var/lib/tarsnap/cache
                - name: tarsnap-secrets
                  mountPath: /var/secrets
          volumes:
            - name: backup
              emptyDir: {}
            - name: tarsnap-cache
              hostPath:
                path: /var/lib/tarsnap/cache
            - name: nfs-data
              hostPath:
                path: /srv/nfs/kubernetes
            - name: postgresql-secrets
              secret:
                secretName: postgresql
            - name: tarsnap-secrets
              secret:
                secretName: tarsnap
