- name: Create syslog config directory
  file:
    path: /usr/local/etc/syslog.d
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Install remote logging config
  copy:
    src: remote.conf
    dest: /usr/local/etc/syslog.d/remote.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Reload syslogd config

- name: Ensure syslogd is started and runs on boot
  service:
    name: syslogd
    enabled: true
    state: started
