- name: Install necessary packages
  package:
    name: syslog-ng
    state: present

- name: Disable syslogd
  copy:
    src: rc.syslogd.conf
    dest: /etc/rc.conf.d/syslogd
    mode: 0644
    owner: root
    group: wheel

- name: Enable syslog-ng
  copy:
    src: rc.syslog_ng.conf
    dest: /etc/rc.conf.d/syslog_ng
    mode: 0644
    owner: root
    group: wheel

- name: Install syslog-ng.conf
  copy:
    src: syslog-ng.conf
    dest: /usr/local/etc/syslog-ng.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Reload syslog-ng config

- name: Ensure syslogd is not running
  service:
    name: syslogd
    state: stopped

- name: Ensure syslog-ng is started and runs at boot
  service:
    name: syslog-ng
    enabled: true
    state: started
