apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nas-cert
  namespace: security
spec:
  secretName: nas-cert
  duration: 17520h
  renewBefore: 360h
  dnsNames:
    - nas.homelab
    - nas
  ipAddresses:
    - 10.0.0.10
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
