- name: Install necessary packages
  package:
    name: '{{ item }}'
    state: present
  loop:
    - bash
    - bazel
    - elixir
    - git
    - gtar
    - node14
    - npm-node14
    - openjdk11-jre
    - postgresql13-server
    - py38-ansible
    - py38-ansible-sysrc
    - yarn-node14

- name: Create teamcity group
  group:
    name: teamcity
    system: true

- name: Create teamcity user
  user:
    name: teamcity
    group: teamcity
    system: true
    home: /opt/TeamCity
    create_home: false

- name: Create /opt directory
  file:
    path: /opt
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Install TeamCity 2021.1.1
  unarchive:
    src: https://download.jetbrains.com/teamcity/TeamCity-2021.1.1.tar.gz
    dest: /opt
    remote_src: true
    creates: /opt/TeamCity
    owner: teamcity
    group: teamcity

- name: Copy TeamCity consul-template config
  copy:
    src: teamcity.hcl
    dest: /usr/local/etc/consul-template.d/teamcity.hcl
    mode: 0644
    owner: root
    group: wheel
  notify: Reload consul-template config
