apiVersion: v1
kind: Service
metadata:
  namespace: storage
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: storage
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.0.3
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.0.4
    ports:
      - port: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: glusterfs-cluster
spec:
  ports:
    - port: 1
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: monitoring
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.0.3
    ports:
      - port: 1
  - addresses:
      - ip: 10.0.0.4
    ports:
      - port: 1
