apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus
    isDefault: true
    version: 1
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
