apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: prometheus
          image: index.docker.io/mmoriarity/prometheus:latest
          resources:
            requests:
              cpu: "200m"
              memory: "750M"
            limits:
              memory: "1250M"
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
