global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - monitoring
          selectors:
            - role: service
              label: app=alertmanager

rule_files:
  - /etc/prom_rules/*.yml

scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['10.0.0.2:3000']
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - action: replace
        source_labels: [__meta_kubernetes_pod_name]
        target_label: kubernetes_pod_name
