global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - consul_sd_configs:
        - services:
            - alertmanager

rule_files:
  - /etc/prom_rules/*.yml

scrape_configs:
  - job_name: consul-services
    consul_sd_configs:
      - {}
    relabel_configs:
      - source_labels: [__meta_consul_service_metadata_metrics_path]
        action: keep
        regex: (.+)
      - source_labels: [__meta_consul_service_metadata_metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_consul_service]
        action: replace
        target_label: service_name
        regex: (.+)
      - source_labels: [__meta_consul_node]
        action: replace
        target_label: node_name
        regex: (.+)

#  - job_name: 'blackbox-dns-public'
#    metrics_path: /probe
#    params:
#      module: [dns_public]
#    static_configs:
#      - targets:
#          - 8.8.4.4
#          - 8.8.8.8
#          - 1.0.0.1
#          - 1.1.1.1
#          - 10.0.0.2
#          - 10.0.0.3
#          - 10.0.0.4
#        labels:
#          probe_type: dns
#          probe_scope: public
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: blackbox-exporter:80
#
#  - job_name: 'blackbox-dns-private'
#    metrics_path: /probe
#    params:
#      module: [dns_private]
#    static_configs:
#      - targets:
#          - 10.0.0.2
#          - 10.0.0.3
#          - 10.0.0.4
#        labels:
#          probe_type: dns
#          probe_scope: private
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: blackbox-exporter:80
#
#  - job_name: 'blackbox-dns-private-cname'
#    metrics_path: /probe
#    params:
#      module: [dns_private_cname]
#    static_configs:
#      - targets:
#          - 10.0.0.2
#          - 10.0.0.3
#          - 10.0.0.4
#        labels:
#          probe_type: dns
#          probe_scope: private-cname
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: blackbox-exporter:80
#
