apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
spec:
  ports:
    - port: 80
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: monitoring
  name: prometheus
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 9090
