apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: prometheus-data-nfs
  annotations:
    nfs.io/storage-path: prometheus-data
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
