apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: tripplite-exporter
  labels:
    app: tripplite-exporter
spec:
  selector:
    matchLabels:
      app: tripplite-exporter
  template:
    metadata:
      labels:
        app: tripplite-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspberrypi
      containers:
        - name: tripplite-exporter
          image: index.docker.io/mmoriarity/tripplite-exporter:latest
          command:
            - /tripplite_exporter
          resources:
            requests:
              cpu: "20m"
              memory: "30M"
            limits:
              memory: "50M"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsGroup: 0
            # necessary to be allowed to read from /dev/bus/usb
            privileged: true
          volumeMounts:
            - name: dev-bus-usb
              mountPath: /dev/bus/usb
      volumes:
        - name: dev-bus-usb
          hostPath:
            path: /dev/bus/usb
