- name: Restart vault agent
  service:
    name: vault-agent
    state: restarted

- name: Reload nginx config
  service:
    name: nginx
    state: reloaded

- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted
