apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  type: NodePort
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      nodePort: 31080
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      nodePort: 31443
      targetPort: https
      protocol: TCP
