apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ingress-nginx
  name: ingress-nginx
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        linkerd.io/inject: ingress
      labels:
        app: ingress-nginx
    spec:
      containers:
        - args:
            - /nginx-ingress-controller
            - ' '
            - --publish-status-address=$(NODE_IP)
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: ingress-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http-metrics
              containerPort: 10254
              protocol: TCP
          resources: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
