apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: ingress
  name: ingress-proxy
  labels:
    app: ingress-proxy
spec:
  selector:
    matchLabels:
      app: ingress-proxy
  template:
    metadata:
      labels:
        app: ingress-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: haproxy
          image: index.docker.io/mmoriarity/ingress-proxy:latest
          resources:
            requests:
              cpu: "50m"
              memory: "50M"
            limits:
              memory: "75M"
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              hostPort: 443
              protocol: TCP
            - name: http-metrics
              containerPort: 9090
              hostPort: 9090
              protocol: TCP
