- name: Install necessary packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - phabricator-php74
    - nginx

- name: Install nginx config
  copy:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: wheel
  notify: Reload nginx config

- name: Install php.ini
  copy:
    src: php.ini
    dest: /usr/local/etc/php.ini
    mode: 0644
    owner: root
    group: wheel
  notify: Restart php-fpm

- name: Install RC config files
  copy:
    src: rc.{{ item }}.conf
    dest: /etc/rc.conf.d/{{ item }}
    mode: 0644
    owner: root
    group: wheel
  loop:
    - nginx
    - php_fpm
    - phd

- name: Copy phabricator local config template
  copy:
    src: local.json.tpl
    dest: /usr/local/etc/phabricator.conf.tpl
    mode: 0644
    owner: root
    group: wheel
  notify: Reload consul-template config

- name: Copy phabricator consul-template config
  copy:
    src: phabricator.hcl
    dest: /usr/local/etc/consul-template.d/phabricator.hcl
    mode: 0644
    owner: root
    group: wheel
  notify: Reload consul-template config

- name: Copy preamble.php
  copy:
    src: preamble.php
    dest: /usr/local/lib/php/phabricator/support/preamble.php
    mode: 0644
    owner: root
    group: wheel

- name: Ensure services are running and start at boot
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - phd
    - php-fpm
    - nginx
