- name: Install Vault
  package:
    name: vault
    state: present

- name: Install Vault RC script
  copy:
    src: vault-agent.sh
    dest: /usr/local/etc/rc.d/vault-agent
    mode: 0755
    owner: root
    group: wheel

- name: Enable Vault agent
  template:
    src: rc.vault_agent.conf.j2
    dest: /etc/rc.conf.d/vault_agent
    mode: 0644
    owner: root
    group: wheel

- name: Install Vault agent configuration
  template:
    src: vault-agent.hcl.j2
    dest: /usr/local/etc/vault-agent.hcl
    mode: 0644
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"

- name: Write Vault role ID
  template:
    src: role_id.j2
    dest: /usr/local/etc/vault_role_id
    mode: 0644
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"

- name: Set permissions for secret ID file
  file:
    state: touch
    path: /usr/local/etc/vault_secret_id
    mode: 0600
    owner: "{{ vault_agent_user }}"
    group: "{{ vault_agent_group }}"
    modification_time: preserve
    access_time: preserve

- name: Ensure Vault agent is running and starts at boot
  service:
    name: vault-agent
    enabled: true
    state: started
