- name: Check if Vault is installed
  stat:
    path: /usr/local/bin/vault
  register: vault_installed

- name: Download Vault
  get_url:
    url: https://releases.hashicorp.com/vault/1.6.1/vault_1.6.1_linux_arm64.zip
    dest: /tmp/vault.zip
  when: vault_installed.stat.exists == false

- name: Unzip Vault into install location
  command:
    cmd: unzip /tmp/vault.zip
    chdir: /usr/local/bin
  become: true
  when: vault_installed.stat.exists == false

- name: Install Vault config file
  copy:
    src: etc_vault.hcl
    dest: /etc/vault.hcl
  become: true
  register: config_file

- name: Install Vault systemd unit
  copy:
    src: vault.service
    dest: /usr/lib/systemd/system/vault.service
    mode: 0644
    owner: root
    group: root
  become: true
  register: systemd

- name: Enable and restart Vault service
  systemd:
    name: vault
    daemon_reload: true
    enabled: true
    state: restarted
  become: true
  when: systemd.changed or config_file.changed

- name: Ensure Vault service is started
  systemd:
    name: vault
    enabled: true
    state: started
  become: true
