apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: pi-hole
  name: named
  labels:
    app: named
spec:
  selector:
    matchLabels:
      app: named
  template:
    metadata:
      labels:
        app: named
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9119"
    spec:
      hostNetwork: true
      shareProcessNamespace: false
      initContainers:
        - name: copy-config-files
          image: index.docker.io/busybox@sha256:94379996c1ea5586ad16a626942dfd427527fb0167cd153c13e64e621f29d258
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - mkdir -p /data/bind/etc && cp -rL /etc/bind/* /data/bind/etc/
          volumeMounts:
            - name: bind-config
              mountPath: /etc/bind
              readOnly: true
            - name: bind-data
              mountPath: /data/bind
        - name: provision-homelab-zones
          image: index.docker.io/mmoriarity/zone-provisioner:latest
          command:
            - /zone-provisioner
            - -node-name
            - $(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /data/bind
              name: bind-data
      containers:
        - name: named
          image: index.docker.io/eafxx/bind@sha256:9c15e971a7a358a4ba248e02154b7d5a6b37803bdf65371325364f3cbae9dd43
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
          env:
            - name: WEBMIN_ENABLED
              value: "false"
            - name: DATA_DIR
              value: "/data"
          resources:
            requests:
              cpu: "50m"
              memory: "150M"
            limits:
              memory: "200M"
          volumeMounts:
            - name: bind-data
              mountPath: /data/bind
        - name: exporter
          image: index.docker.io/prometheuscommunity/bind-exporter@sha256:24424c6a00264f4e3a9af6f2f4bb4be717594171903f84812982ef46f6733ccc # 0.3.0
          ports:
            - name: http
              containerPort: 9119
              protocol: TCP
      volumes:
        - name: bind-data
          emptyDir: {}
        - name: bind-config
          configMap:
            name: bind-config
