- name: Create CNI plugins directory
  file:
    path: /opt/cni/bin
    state: directory
  become: true

- name: Check if the CNI plugins are installed
  stat:
    path: /opt/cni/bin/bridge
  register: cni_installed

- name: Download CNI plugins
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.9.0/cni-plugins-linux-arm64-v0.9.0.tgz
    dest: /tmp/cni.tgz
  when: cni_installed.stat.exists == false

- name: Unzip CNI plugins
  command:
    cmd: tar -C /opt/cni/bin -xzf /tmp/cni.tgz
  become: true
  when: cni_installed.stat.exists == false

- name: Check current Nomad version
  shell:
    cmd: nomad version | grep -oP '(?<=Nomad v)([^ ]+)' || echo "none"
  register: installed_nomad_version
  changed_when: false

- name: Install Nomad {{ nomad_version }}
  unarchive:
    src: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm64.zip
    dest: /usr/local/bin
    remote_src: true
  become: true
  when: installed_nomad_version.stdout != nomad_version
  notify: Restart Nomad service

- name: Ensure Nomad data directory exists
  file:
    path: /var/lib/nomad
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Ensure Promtail run directory exists
  file:
    path: /var/lib/promtail
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Install Nomad config file
  copy:
    src: etc_nomad.hcl
    dest: /etc/nomad.hcl
    mode: 0644
    owner: root
    group: root
  notify: Restart Nomad service

- name: Install Nomad environment file
  template:
    src: nomad.env.j2
    dest: /etc/nomad.env
    mode: 0600
    owner: root
    group: root
  notify: Restart Nomad service

- name: Install Nomad systemd unit
  copy:
    src: nomad.service
    dest: /usr/lib/systemd/system/nomad.service
    mode: 0644
    owner: root
    group: root
  become: true
  notify: Restart Nomad service

- name: Ensure Nomad service is started
  systemd:
    name: nomad
    enabled: true
    state: started
  become: true
