- name: Install DNS config
  copy:
    src: etc_resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: '{{ hostvars[inventory_hostname]["root_group"] }}'
  become: true

- name: Set up BIND server
  include_tasks: named.yml
  when: setup_named

- name: Set up packet filter rules
  include_tasks: pf.yml
  when: setup_pf
