- name: Install necessary packages
  package:
    name: "{{ item }}"
    state: present
  loop: [bind916, bind_exporter, consul-template]

- name: Configure named
  template:
    src: named.conf.j2
    dest: '{{ named_db_dir }}/named.conf'
  become: true
  notify: Reload named config

- name: Configure named default zones
  template:
    src: named.default-zones.conf.j2
    dest: '{{ named_db_dir }}/named.default-zones.conf'
  become: true
  notify: Reload named config

- name: Configure named forwarders
  copy:
    src: named.forwarders.conf.tpl
    dest: '{{ named_db_dir }}/named.forwarders.conf.tpl'
    mode: 0644
    owner: root
    group: wheel
  become: true
  notify: Reload consul-template config

- name: Configure zone DBs
  template:
    src: "{{ item }}.db.tpl.j2"
    dest: "{{ named_db_dir }}/master/{{ item }}.db.tpl"
    mode: 0644
    owner: root
    group: wheel
  become: true
  notify: Reload consul-template config
  loop: '{{ zone_names | product(zone_variants) | map("join", ".") }}'

- name: Create consul-template config directory
  file:
    path: /usr/local/etc/consul-template.d
    state: directory
    mode: 0700
    owner: root
    group: wheel

- name: Configure consul-template
  copy:
    src: dns.hcl
    dest: /usr/local/etc/consul-template.d/dns.hcl
    mode: 0644
    owner: root
    group: wheel
  become: true
  notify: Reload consul-template config

- name: Ensure services are running and start at boot
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: [named, bind_exporter, consul-template]
