global:
  resolve_timeout: 5m

templates:
  - << env "NOMAD_TASK_DIR" >>/templates/*.tpl

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: pagerduty

receivers:
  - name: 'push.phone.matt'
    pushover_configs:
<<- with secret "kv/pushover" >>
      - user_key: << .Data.data.user_key >>
        token: << .Data.data.token >>
<<- end >>
        title: '{{ template "pushover.title" . }}'
        priority: '{{ template "pushover.priority" . }}'
  - name: pagerduty
    pagerduty_configs:
      - routing_key: << with secret "kv/pagerduty" >><< .Data.data.routing_key >><< end >>
        severity: '{{ template "pagerduty.severity" . }}'

inhibit_rules: []
