- hosts: artemis
  remote_user: matt
  become: true
  roles:
    - role: pkg
    - role: logging
    - role: jail
    - role: dns
    - role: consul
    - role: mail

- hosts: jails
  become: true
  gather_facts: false
  roles:
    - role: pkg
    - role: logging
    - role: dns

- hosts: metrics1
  become: true
  gather_facts: false
  roles:
    - role: prometheus

- hosts: minio1
  become: true
  gather_facts: false
  roles:
    - role: minio

- hosts: paperless1
  become: true
  gather_facts: false
  roles:
    - role: paperless

- hosts: code1
  become: true
  gather_facts: false
  roles:
    - role: phabricator
