- hosts: artemis
  remote_user: matt
  become: true
  roles:
    - role: pkg
    - role: logging
    - role: nut
    - role: jail
    - role: dns
    - role: consul
    - role: mail

- hosts: jails
  become: true
  gather_facts: false
  roles:
    - role: pkg
    - role: logging
    - role: dns

- hosts: metrics1, paperless1, dns, code1, ci1
  become: true
  gather_facts: false
  roles:
    - role: consul-template

- hosts: metrics1
  become: true
  gather_facts: false
  roles:
    - role: prometheus

- hosts: minio1
  become: true
  gather_facts: false
  roles:
    - role: minio

- hosts: paperless1
  become: true
  gather_facts: false
  roles:
    - role: paperless

- hosts: code1
  become: true
  gather_facts: false
  roles:
    - role: phabricator

- hosts: redis1
  become: true
  roles:
    - role: redis

- hosts: ci1
  become: true
  roles:
    - role: teamcity

- hosts: homelab1
  become: true
  roles:
    - role: homelab
