- hosts: artemis
  remote_user: matt
  become: true
  roles:
    - role: logging
    - role: jail
    - role: dns
      vars:
        setup_pf: true
    - role: consul

- hosts: jails
  become: true
  gather_facts: false
  roles:
    - role: logging
    - role: dns

- hosts: metrics
  become: true
  gather_facts: false
  roles:
    - role: prometheus

- hosts: minio
  become: true
  gather_facts: false
  roles:
    - role: minio
