apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deploy
  name: deploy-srv
  labels:
    app: deploy-srv
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: deploy-srv
  template:
    metadata:
      labels:
        app: deploy-srv
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8480"
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: deploy-srv
          image: index.docker.io/mmoriarity/deploy-srv:latest
          command:
            - /deploy-srv
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              memory: "200M"
          ports:
            - name: http
              containerPort: 8480
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            successThreshold: 3
            timeoutSeconds: 3
            periodSeconds: 15
          volumeMounts:
            - name: deploy-secrets
              mountPath: /var/secrets
      volumes:
        - name: deploy-secrets
          secret:
            secretName: deploy
