apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-links
  name: go-links-srv
  labels:
    app: go-links
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: go-links
  template:
    metadata:
      labels:
        app: go-links
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: go-links-srv
          image: index.docker.io/mmoriarity/go-links-srv:latest
          command:
            - /go-links
            - -db="dbname=golinks user=golinks host=postgresql.storage"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-links
                  key: db-password
          ports:
            - name: http
              containerPort: 4240
