name: Test and push images

on:
  push:
    branches: [main, nomad]

jobs:
  build:
    name: "Test and push"
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Bazel outputs
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel/disk-cache
          key: bazel-images-${{ github.sha }}
          restore-keys: |
            bazel-images-
      - name: Install Bazel
        run: |
          sudo curl -L https://github.com/bazelbuild/bazel/releases/download/3.7.0/bazel-3.7.0-linux-x86_64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
      - name: Login to Docker
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        run: bazel test --config=ci --build_tests_only //...
      - name: Build and push container images
        run: |
          bazel query 'kind(container_push, //...)' \
            | xargs -n1 bazel run --config=ci --platforms @io_bazel_rules_go//go/toolchain:linux_arm64
