name: iOS

on:
  push:
    branches: [main]

jobs:
  build_presence:
    name: "Build Presence app"
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Bazel outputs
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel/disk-cache
          key: bazel-ios-${{ github.sha }}
          restore-keys: |
            bazel-ios-
      - name: Install Bazel
        run: |
          sudo curl -L https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel-3.7.1-darwin-x86_64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
      - name: Build Presence app
        run: bazel build --config=ci //detect-presence/ios:ios_ad_hoc
