name: Kubernetes

on:
  push:
    branches: [main]

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Bazel outputs
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel/disk-cache
          key: bazel-k8s-${{ github.sha }}
          restore-keys: |
            bazel-k8s-
      - name: Install Bazel
        run: |
          sudo curl -L https://github.com/bazelbuild/bazel/releases/download/3.7.0/bazel-3.7.0-linux-x86_64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
      - name: Login to Docker
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        run: bazel test --config=ci --build_tests_only //...
      - name: Build and generate Kubernetes manifests
        run: bazel run --config=ci --platforms @io_bazel_rules_go//go/toolchain:linux_arm64 //:k8s > /tmp/k8s.yaml
      - name: Build and generate Kubernetes CRD manifests
        run: bazel run --config=ci --platforms @io_bazel_rules_go//go/toolchain:linux_arm64 //:k8s_crds > /tmp/k8s_crds.yaml

      - name: Store Kubernetes manifests
        uses: actions/upload-artifact@v2
        with:
          name: all_k8s
          path: |
            /tmp/k8s.yaml
            /tmp/k8s_crds.yaml
          if-no-files-found: error
