- name: Create pihole-data volume mountpoint
  file:
    path: /srv/mnt/pihole-data
    state: directory
    mode: 0700
    owner: root
    group: root
  become: true

- name: Mount pihole-data volume
  ansible.posix.mount:
    path: /srv/mnt/pihole-data
    src: 127.0.0.1:/pihole-data
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted
  become: true
